### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by johnpaliotta**
Fixed issue: #56, removed left-over code from an earlier implementation of code-based testing

### CODE REVIEW

**Comment by johnpaliotta** [comment]
@igor, This patch removes the --kind flag, hope this does not break any of your tests.

**Review by Zbigor — APPROVED** [review]
All good, changes don't affect the tests

**Comment by Zbigor** [comment]
> All good, changes don't affect the tests

This was tested before merging the previous PR into main, I see now that there are some merge conflicts

**Comment by Zbigor** [comment]
> > All good, changes don't affect the tests
> 
> This was tested before merging the previous PR into main, I see now that there are some merge conflicts

Still all good after merge conflicts resolution

**Pull request merged**
