### PR TITLE
Fixed issue #215, made improvements to test result reporting

### PR DESCRIPTION
**Pull request by johnpaliotta**

### CODE REVIEW

**Comment by johnpaliotta** [comment]
@Den1552 Looks like we have some timeouts ... at least for the first 2 I checked, could you take a look please?

**Comment by Den1552** [comment]
@johnpaliotta Sure thing, will do :)

**Comment by Den1552** [comment]
@johnpaliotta I made a PR that changes the expected logs. I replaced the deleted logs with other message pane logs to ensure that the process did not fail. 

https://github.com/vectorgrp/vector-vscode-vcast/pull/219

**Comment by johnpaliotta** [comment]
> @johnpaliotta I made a PR that changes the expected logs. I replaced the deleted logs with other message pane logs to ensure that the process did not fail.

@Den1552 the stuff that was in the message pane for the failed test case is now in the "Test Results" pane in both pass and fail cases.  Are you able to check the contents of this pane?

image

**Comment by Den1552** [comment]
@johnpaliotta Sure, I will adjust the code.

**Pull request merged**
